### PR TITLE
Support Swift 2.0

### PR DESCRIPTION
**Pull request by mcudich**
I assume you want to create a new branch based on this and not just update master?

### CODE REVIEW

**Comment by joshaber** [comment]
Absolutely :metal: Thanks!

**Comment by joshaber** [comment]
Oops sorry, misread this.

**Comment by joshaber** [comment]
https://github.com/joshaber/SwiftBox/tree/swift-2.0 :boom:

**Comment by mcudich** [comment]
Sweet! Thanks Josh.

**Comment by joshaber** [comment]
Thank you!

**Pull request merged**
