### PR TITLE
Xcode 7 beta 6 fixes

### PR DESCRIPTION
**Pull request by mcudich**

### CODE REVIEW

**Comment by joshaber** [comment]
:metal: Thanks!

**Comment by mcudich** [comment]
Sweet!

By the way, I have another branch ready that updates SwiftBox to the latest
css-layout changes. Interested in taking a look?

**Comment by joshaber** [comment]
Absolutely!

**Comment by mcudich** [comment]
Sweet. Before I send it, one thing I noticed is that you use tab-based
whitespace. Is that intentional?

**Comment by joshaber** [comment]
Yup! I follow https://github.com/github/swift-style-guide.

**Comment by mcudich** [comment]
Sounds good. I'll send it over as soon as I convert my spaces to tabs :)

**Pull request merged**
